default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.19
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: local
    # it should be installed using uv sync
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        args: [ ]
        language: system
        types: [ python ]